#if PIXYZ_PLUGIN_FOR_UNITY
using UnityEngine;
using UnityEditor.Toolbars;

namespace UnityEditor.PixyzPlugin4Unity.Toolbox
{
	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems
	{
		[EditorToolbarElement(id, typeof(SceneView))]
		class MeshToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "Mesh";
			protected override string GroupName => "Mesh";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1),
				() => Select(2),
				() => Select(3),
				() => Select(4),
				() => Select(5)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.ConformNormals, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.FlipNormals, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.RepairMesh, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.RemoveZFighting, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.CreateNormals, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.BakeAmbientOcclusion, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Conform Normals", "Flip Normals", "Repair", "Remove Z-Fighting", "Create Normals (smoothness)", "Bake Ambient Occlusion" };
			protected override string[] ActionNames => m_ActionNames;

		}
		[EditorToolbarElement(id, typeof(SceneView))]
		class OptimizeToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "Optimize";
			protected override string GroupName => "Optimize";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1),
				() => Select(2),
				() => Select(3)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.Decimate, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.RemoveOccluded, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.RemoveHoles, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.BakeMaterials, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Decimate", "Remove Occluded", "Remove Holes", "Bake Materials" };
			protected override string[] ActionNames => m_ActionNames;

		}
		[EditorToolbarElement(id, typeof(SceneView))]
		class RemeshingToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "Remeshing";
			protected override string GroupName => "Remeshing";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1),
				() => Select(2)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.Retopologize, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.BakeImpostor, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.BakeBillboard, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Retopologize", "Create Impostor", "Create Billboard" };
			protected override string[] ActionNames => m_ActionNames;

		}
		[EditorToolbarElement(id, typeof(SceneView))]
		class HierarchyToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "Hierarchy";
			protected override string GroupName => "Hierarchy";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1),
				() => Select(2)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.ExplodeSubmeshes, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.Merge, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.ReplaceBy, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Explode", "Merge", "Replace by..." };
			protected override string[] ActionNames => m_ActionNames;

		}
		[EditorToolbarElement(id, typeof(SceneView))]
		class TransformToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "Transform";
			protected override string GroupName => "Transform";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1),
				() => Select(2)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.MovePivot, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.SnapToGround, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.CenterToOrigin, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Move Pivot", "Snap To Ground", "Center to Origin" };
			protected override string[] ActionNames => m_ActionNames;

		}
		[EditorToolbarElement(id, typeof(SceneView))]
		class UVsToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "UVs";
			protected override string GroupName => "UVs";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.CreateUVs, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.CreateLightmapUVs, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Create UVs", "Create UVs for Lightmaps" };
			protected override string[] ActionNames => m_ActionNames;

		}
		[EditorToolbarElement(id, typeof(SceneView))]
		class CollidersToggle : PixyzEditorToolbarDropdown
		{
			public const string id = "Colliders";
			protected override string GroupName => "Colliders";
			protected override GenericMenu.MenuFunction[] MenuFunctions => new GenericMenu.MenuFunction[] {
				() => Select(0),
				() => Select(1)
			};
			private readonly System.Type[] m_Actions = new System.Type[] {
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.CreateCollider, Unity.Pixyz.Plugin4Unity.Editor"),
				System.Type.GetType("UnityEditor.PixyzPlugin4Unity.Actions.RemoveColliders, Unity.Pixyz.Plugin4Unity.Editor")
			};
			protected override System.Type[] Actions => m_Actions;

			private readonly string[] m_ActionNames = new string[] { "Create Collider", "Remove Colliders" };
			protected override string[] ActionNames => m_ActionNames;

		}
	}
}
#endif